---

name: Merge

on:
  push:
    branches:
      - master

jobs:
  deploy_flatpak:
    name: Deploy Flatpak
    runs-on: ubuntu-latest

    container:
      image: bilelmoussaoui/flatpak-github-actions:elementary-juno
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
        with:
          bundle: calculator.flatpak
          manifest-path: io.elementary.calculator.yml
          run-tests: true
          repository-name: elementary
          repository-url: https://flatpak.elementary.io/elementary.flatpakrepo
          cache-key: "flatpak-builder-${{ github.sha }}"

      - name: Deploy
        uses: bilelmoussaoui/flatpak-github-actions/flat-manager@v3
        with:
          repository: elementary
          flat-manager-url: https://flatpak-api.elementary.io
          token: ${{ secrets.FLAT_MANAGER_TOKEN }}

  gettext:
    name: Gettext
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_USER_TOKEN }}

      - name: Gettext
        uses: elementary/actions/gettext-template@master
